### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by Smargendorf** [sioodmy/todo#10]
It would be awesome if this could run on macos!

From what I can tell, the current build panics at line 25 of lib.rs if ran on mac.
I tried changing the match statement to include 'macos', but only ran into further errors.

**Comment by ezdux** [comment]
Can you show the error?

**Comment by ezdux** [comment]
#11 should be a fix

**Comment by Smargendorf** [comment]
I tried your code, but I got the same error that I got when I tried adding 'macos' to the match statement. And you're right, I should be showing these errors, so here is the error I get when I try to run your new branch:

➜  todo git:(master) cargo build --release
   Compiling libc v0.2.103
   Compiling lazy_static v1.4.0
   Compiling atty v0.2.14
   Compiling colored v2.0.0
   Compiling todo v0.1.0 (/Users/me/Workspace/todo)
    Finished release [optimized] target(s) in 1.14s
➜  todo git:(master) sudo cp target/release/todo /usr/local/bin 
➜  todo git:(master) todo
[1]    9878 killed     todo

**Comment by ezdux** [comment]
Did you meant to run this instead?
```sh
$ cp target/release/todo /usr/local/bin/todo
```
