### ISSUE TITLE
Feature Request: Allow for variable TODO file paths

### ISSUE THREAD

**Issue by tosti007** [sioodmy/todo#13]
Hey there!

I saw a post on r/linux or r/rust some days ago and have been using it since, thank you so much! With the new mac support PR (I think) the TODO file path has been changed from the current directory to the HOME directory (at least on my pc, which in hindsight after looking at the code was the intended behavior all along).

Anyhow, I like to have my TODO's split across multiple categories/projects, which was nicely possible with the "local folder TODO file" behavior. Would it be possible to add something like a flag to point to a file to use as TODO file?

I figured I would open an issue first to talk about the best way to do this (e.g. by a `-f` flag or having an optional argument before the action that denotes the file).

**Comment by yonderbread** [comment]
Being able to make multiple lists would be nice too.

**Comment by sioodmy** [comment]
Added `TODO_PATH` env variable
