### ISSUE TITLE
[bug] `todo` Couldn't open the todofile

### ISSUE THREAD

**Issue by NChechulin** [sioodmy/todo#16]
`todo version: 2.3.1`

Steps to reproduce:

while in `/home/username/`:
```sh
todo add "something"
cd Documents
todo done 1
```

output:

```
thread 'main' panicked at 'Couldn't open the todofile: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/lib.rs:226:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

~As far as I understand, `todo` creates a file in my home directory by default and when called from another directory it cannot access it.~
By some weird reason `todo list` works fine
It seems a little bit weird, since I remember seeing `TODO` files in other directories.

So, I assume that the creation process is somehow wrong.

If any extra information / logs needed, then please be kind to provide some instructions on getting them.

**Comment by sioodmy** [comment]
Fixed in the newest release
