### ISSUE TITLE
Wrong Numbering

### ISSUE THREAD

**Issue by eingorz** [sioodmy/todo#3]
Ok so I'm not sure if this is me just being dumb but the numbering seems to be wrong?
I added 3 todos and instead of them being numbered 1 2 3 they were numbered 1 3 5

**Comment by eingorz** [comment]
Here's a screenshot of it
https://imgur.com/a/7j2xRyR
btw really cool project I'm definitely going to use this on a daily basis :D

**Comment by sioodmy** [comment]
Could you please show the output of `cat TODO`?

**Comment by sioodmy** [comment]
The problem is that the program did not expect that a line in the TODO file might not begin with the appropriate symbol

**Comment by eingorz** [comment]
Sorry for a late reply, cat todo returns:

   ein  aryan [~]  $  cat TODO
[ ] Študýruj děják

[ ] Udělej prezentaci na JFK

[ ] Udělej referát do Zeměpisu a Přírodopisu

   ein  aryan [~]  $

**Comment by sioodmy** [comment]
Fixed, affected users should remove empty lines from their TODO file
I have changed the method of adding new tasks, so this bug won't occur in the future
