### ISSUE TITLE
Unable to run the project

### ISSUE THREAD

**Issue by akshatpatel21** [sioodmy/todo#31]
I cloned the project in VS code but when i am trying to run it in visual studio code terminal like "todo orange banana" it says todo command not found. so help me out how to run it.

**Comment by sioodmy** [comment]
show me your PATH env variable

**Comment by akshatpatel21** [comment]
<img width="1440" alt="Screenshot 2023-12-10 at 4 23 41 PM" src="https://github.com/sioodmy/todo/assets/153410918/6d0814c5-3af1-476e-84dd-2a4fe2456358">


and i am going to add some new features like working with ductdb database side which helps input to be inserted into database like database operations insert, update, delete.

**Comment by sioodmy** [comment]
you should probably run it with ./target/debug/todo or sth

**Comment by akshatpatel21** [comment]
so what shouls i have to do to run it!?

**Comment by sioodmy** [comment]
> and i am going to add some new features like working with ductdb database side which helps input to be inserted into database like database operations insert, update, delete.

sounds like a fun project, but TODO is a front end for human readable plain text file, so keep in mind I won't accept PR with such a feature

**Comment by sioodmy** [comment]
> so what shouls i have to do to run it!?

cargo run should work

**Comment by akshatpatel21** [comment]
okay let me see how i am gonna resolve it.
